[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["node_modules/bcrypt/**"]

[functions."api/*"]
  included_files = ["prisma/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[plugins]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
  node_bundler = "esbuild"
  [plugins.environment]
    NODE_OPTIONS = "--require polka --require ts-node/register"
    NODE_ENV = "development"

[build]
  command = "npm run build"
  publish = ".next"
  node_bundler = "esbuild"
  api = "./api"
  [build.environment]
    DATABASE_URL = "your_database_url"
    DATABASE_PASSWORD = "your_database_password"
    NODE_VERSION = "your_node_version"
  [build.processing]
    esbuild = { externalModules = ["node-fetch", "crypto"] }

[functions.timeout]
  duration = 30