[functions]
  node_bundler = "esbuild"

[functions."api/*"]
  included_files = ["prisma/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[build]
  command = "npm run build"
  publish = ".next"

[functions.timeout]
  duration = 30