[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  timeout = 30

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "14"

[functions."api/*"]
  included_files = ["prisma/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[build]
  command = "npm run build"
  publish = ".next"